export const dummyUsers=[

    { id:1,
      email:'LibraJames@yahoo.com',
      isAdmin: false,
      first_name:'Libra',
      last_name:'James',
      created_at:'',
      updated_at:'',
    },
    { id:2,
      email:'Christina_Paul@gmail.com',
      isAdmin: false,
      first_name:'Christina',
      last_name:'Paul',
      created_at:'',
      updated_at:'',
    },
    { id:3,      
      email:'gigi-bryant@yahoo.com',
      isAdmin: false,
      first_name:'Gigi',
      last_name:'Bryant',
      created_at:'',
      updated_at:'',
    },
    { id:4,      
      email:'M_J@outlook.com',
      isAdmin: false,
      first_name:'Michelle',
      last_name:'Jordan',
      created_at:'',
      updated_at:'',
    },
    { id:5,      
      email:'D-wade@gmail.com',
      isAdmin: false,
      first_name:'Diana',
      last_name:'Wade',
      created_at:'',
      updated_at:'',
    },
    { id:6,      
      email:'Chrisette-b@yahoo.com',
      isAdmin: false,
      first_name:'Chrisette',
      last_name:'Bosh',
      created_at:'',
      updated_at:'',
    },
    { id:7,      
      email:'ms-oneal@outlook.com',
      isAdmin: false,
      first_name:'Shanise',
      last_name:'Oneal',
      created_at:'',
      updated_at:'',
    },
    { id:8,      
      email:'aly-iverson@yahoo.com',
      isAdmin: false,
      first_name:'Alice',
      last_name:'Iverson',
      created_at:'',
      updated_at:'',
    },
    { id:9,      
      email:'carmen.anthony@gmail.com',
      isAdmin: false,
      first_name:'Carmen',
      last_name:'Anthony',
      created_at:'',
      updated_at:'',
    },
    { id:10,      
      email:'CharlieBark@zoho.net',
      isAdmin: false,
      first_name:'Charlotte',
      last_name:'Barkley',
      created_at:'',
      updated_at:'',
    },
    { id:11,      
      email:'BriDavis@gmail.com',
      isAdmin: false,
      first_name:'Brianna',
      last_name:'Davis',
      created_at:'',
      updated_at:'',
    },
    ]

    export const dummyItems=[    
        {id: 1,
        product_name: "Oranges",
        price: 3.00,
        city: "Miami",
        category: "citrus",
        description: "Fresh oranges perfect for juicing",
        unit: "dollars",
        // image_url: "https://tinyurl.com/y6jr6etj",
        user_id: 6
      },
      {id: 2,
        product_name: "Rice",
        price: 2.00,
        city: "Manhattan",
        category: "grain",
        description: "Organic wild rice",
        unit: "dollars",
        // image_url: "https://tinyurl.com/y6jr6etj",
        user_id: 9
      },
      {id: 3,
        product_name: "Avocado",
        price: 5.00,
        city: "Los Angeles",
        category: "Fruits",
        description: "Ripe hass avocados",
        unit: "dollars",
        // image_url: "https://tinyurl.com/y6jr6etj",
        user_id: 4
      },
      {id: 4,
        product_name: "Plantains",
        price: 6.00,
        city: "San Juan",
        category: "Fruits",
        description: "Organic plantains",
        unit: "dollars",
        // image_url: "https://tinyurl.com/y6jr6etj",
        user_id: 1
      },
      {id: 5,
        product_name: "Peaches",
        price: 3.00,
        city: "Atlanta",
        category: "Fruits",
        description: "Homegrown Georgia peaches",
        unit: "dollars",
        // image_url: "https://tinyurl.com/y6jr6etj",
        user_id: 11
      },
    ]
    